#!/bin/bash
xrandr --output DVI-I-1 --off --output HDMI-0 --auto
export PYTHONPATH=/usr/lib/pyshared/python2.7 

# Start basic window manager and video settings
xfwm4 --replace --daemon --compositor=off

sudo setup_xboxdrv &

xcompmgr &
xmodmap -e 'keycode 172 = space'
xmodmap -e 'keycode 122 = 9'
xmodmap -e 'keycode 123 = 0'
xmodmap -e 'keycode 166 = Escape'

#~/vcs/upmc/main.py --music-url "http://music/ch%02d.mp3" --channels 3 /srv/media/Video 
x-terminal-emulator

sudo setup_xboxdrv --shutdown
