#!/bin/bash
xrandr --output DVI-I-1 --off --output HDMI-0 --auto # Pygame is horrible with multi-displays.
export PYTHONPATH=/usr/lib/pyshared/python2.7 # Some bug in 12.10 and 13.04 is causing this directory to not be included in Python's default path.

xfwm4 --replace --daemon --compositor=on # Still not sure which WM I'll stick with, but this seems to work for now.

sudo setup_xboxdrv & # Start the xboxdrv daemon so that the wireless Xbox 360 controllers work

## Remap some of the media keys, because UPMC ignores them.
xmodmap -e 'keycode 172 = space'
xmodmap -e 'keycode 122 = 9'
xmodmap -e 'keycode 123 = 0'
xmodmap -e 'keycode 166 = Escape'

upmc --music /srv/media/Video # Finally, start UPMC
#x-terminal-emulator #DEBUG#

sudo setup_xboxdrv --shutdown # Stop the xboxdrv daemon.
